records: [{
    "name": "",
    "sort": 0,
    "match": "find.qq.com/index.html",
    "action": "./__index.html",
    "checked": true,
    "id": null,
    "parentId": null,
    "leaf": true
}, {
    "name": "",
    "sort": 4,
    "match": "find.qq.com/css/comp.css",
    "action": "./css/main.css|./css/sub1.css",
    "checked": true,
    "id": null,
    "parentId": null,
    "leaf": true
}, {
    "name": "",
    "sort": 5,
    "match": "find.qq.com/js/catalog.js",
    "action": "http://pub.idqqimg.com/qqfind/js/groupcatalog.js",
    "checked": true,
    "id": null,
    "parentId": null,
    "leaf": true
}, {
    "name": "",
    "sort": 3,
    "match": "find.qq.com/js/find.combo.js",
    "action": "./js/jquery.js|./js/main.js",
    "checked": true,
    "id": null,
    "parentId": null,
    "leaf": true
}, {
    "name": "",
    "sort": 1,
    "match": "find.qq.com/|*.idqqimg.com/qqfind/",
    "action": "./",
    "checked": true,
    "id": null,
    "parentId": null,
    "leaf": true
}, {
    "name": "",
    "sort": 2,
    "match": "find.qq.com/js/find.all.js",
    "action": "./tools/find.all.qzmin",
    "checked": true,
    "id": null,
    "parentId": null,
    "leaf": true
}]
